version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      #- yum update -y
      - yum install jq
      - pip install taskcat
  pre_build:
    commands:
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' aws_credentials.json)
      - export AWS_SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' aws_credentials.json)
      - export AWS_SESSION_TOKEN=$(jq -r '.Token' aws_credentials.json)
      - rm aws_credentials.json
      - aws configure set role_arn $MGT_ASSUME_ROLE_ARN --profile $MGT_PROFILE_NAME
      - aws configure set credential_source Environment --profile $MGT_PROFILE_NAME
      - aws configure set role_arn $LOGARCHIVE_ASSUME_ROLE_ARN --profile $LOGARCHIVE_PROFILE_NAME
      - aws configure set credential_source Environment --profile $LOGARCHIVE_PROFILE_NAME
      - mkdir -p .taskcat/output
  build:
    commands:
      - echo Starting test $(date) in $(pwd)
      - bash .ci/run-taskcat.sh test .taskcat/output
  post_build:
    commands:
      - echo Starting cleanup $(date) in $(pwd)
      - bash .ci/run-cleanup.sh $MGT_PROFILE_NAME
      - bash .ci/run-cleanup.sh $LOGARCHIVE_PROFILE_NAME
artifacts:
  files:
      - '**/*'